import { StyleSheet } from 'react-native';
import { colors, radii, spacing } from '../../theme';

export const supportStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  header: { minHeight: 64, backgroundColor: colors.brand, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.lg, gap: 12 },
  back: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { color: colors.white, fontSize: 20, fontWeight: '800', flex: 1, textAlign: 'center' },
  content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 40 },
  search: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.sm, padding: 14, fontSize: 15, color: colors.text },
  hero: { backgroundColor: colors.brandDark, borderRadius: radii.md, padding: spacing.xl, gap: 8 },
  heroTitle: { color: colors.white, fontSize: 22, fontWeight: '800' },
  heroText: { color: '#D9E5EC', lineHeight: 20 },
  button: { backgroundColor: colors.brand, minHeight: 48, borderRadius: radii.sm, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  buttonText: { color: colors.white, fontWeight: '800' },
  secondaryButton: { backgroundColor: colors.brandMist },
  secondaryText: { color: colors.brandDark, fontWeight: '800' },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.sm, padding: spacing.lg, gap: 8 },
  cardTitle: { color: colors.text, fontWeight: '800', fontSize: 15 },
  ticketListCard: { position: 'relative', overflow: 'hidden', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.md, paddingLeft: spacing.xl, paddingRight: spacing.lg, paddingVertical: spacing.lg, gap: 7 },
  ticketListCardClosed: { backgroundColor: '#FAFBFB', borderColor: '#E5E8EA' },
  ticketListAccent: { position: 'absolute', left: 0, top: 0, bottom: 0, width: 5 },
  ticketListHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  ticketListCode: { flex: 1, minWidth: 0, color: colors.text, fontWeight: '800', fontSize: 15 },
  ticketListStatus: { flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: radii.pill, paddingHorizontal: 10, paddingVertical: 6 },
  ticketListStatusText: { fontSize: 11, lineHeight: 15, fontWeight: '800' },
  ticketListSubject: { color: colors.textBody, fontSize: 15, lineHeight: 21, fontWeight: '600' },
  ticketListDescription: { fontSize: 12, lineHeight: 17, fontWeight: '700' },
  ticketListFooter: { flexDirection: 'row', alignItems: 'center', gap: 5, marginTop: 2 },
  ticketListTime: { flex: 1, color: colors.textSubtle, fontSize: 11, lineHeight: 16 },
  ticketListTextClosed: { color: colors.textMuted },
  muted: { color: colors.textMuted, lineHeight: 20 },
  faqAnswer: { color: colors.textBody, lineHeight: 21, paddingTop: 6 },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  badge: { backgroundColor: colors.coral, minWidth: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  badgeText: { color: colors.white, fontWeight: '800', fontSize: 12 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { paddingVertical: 9, paddingHorizontal: 12, borderRadius: 999, backgroundColor: colors.brandMist },
  chipActive: { backgroundColor: colors.brand },
  chipText: { color: colors.brandDark, fontWeight: '700', fontSize: 12 },
  chipTextActive: { color: colors.white },
  input: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.sm, padding: 14, color: colors.text, fontSize: 15 },
  label: { color: colors.text, fontWeight: '800', marginBottom: -6 },
  error: { backgroundColor: colors.dangerSoft, color: colors.danger, padding: 12, borderRadius: radii.sm },
  success: { backgroundColor: colors.brandMist, color: colors.brandDark, padding: 12, borderRadius: radii.sm },
  imageRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  image: { width: 80, height: 80, borderRadius: radii.sm, backgroundColor: colors.brandMist },
  chatLayout: { flex: 1, backgroundColor: '#F3F6F8' },
  detailHeaderTitleGroup: { flex: 1, minWidth: 0 },
  detailHeaderTitle: { color: colors.white, fontSize: 17, lineHeight: 22, fontWeight: '800' },
  detailHeaderSubtitle: { color: 'rgba(255,255,255,0.72)', fontSize: 11, lineHeight: 15 },
  connectionStatus: { alignItems: 'center', justifyContent: 'center', minWidth: 50, gap: 2 },
  connectionDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#4ADE80' },
  connectionDotOffline: { backgroundColor: 'rgba(255,255,255,0.48)' },
  connectionText: { color: 'rgba(255,255,255,0.78)', fontSize: 9, fontWeight: '700' },
  chatError: { marginHorizontal: spacing.md, marginTop: spacing.sm, backgroundColor: colors.dangerSoft, color: colors.danger, paddingHorizontal: spacing.md, paddingVertical: 9, borderRadius: radii.sm, fontSize: 13 },
  ticketSummary: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: colors.surface, borderBottomWidth: 1, borderBottomColor: colors.border, paddingHorizontal: spacing.lg, paddingVertical: 11 },
  ticketIcon: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.brandSoft },
  ticketSummaryCopy: { flex: 1, minWidth: 0 },
  ticketCode: { color: colors.textMuted, fontSize: 10, lineHeight: 14, fontWeight: '800', letterSpacing: 0.5 },
  ticketSubject: { color: colors.text, fontSize: 14, lineHeight: 20, fontWeight: '800' },
  statusPill: { maxWidth: 132, minHeight: 28, flexDirection: 'row', alignItems: 'center', gap: 4, borderRadius: radii.pill, paddingHorizontal: 9, paddingVertical: 5 },
  statusPillText: { flexShrink: 1, fontSize: 10, lineHeight: 14, fontWeight: '800' },
  messagesScroll: { flex: 1 },
  messagesContent: { flexGrow: 1, justifyContent: 'flex-end', paddingHorizontal: spacing.md, paddingTop: spacing.lg, paddingBottom: spacing.xl, gap: 10 },
  messageRow: { width: '100%', flexDirection: 'row', alignItems: 'flex-end', gap: 7 },
  messageRowCustomer: { justifyContent: 'flex-end', paddingLeft: 46 },
  messageRowStaff: { justifyContent: 'flex-start', paddingRight: 46 },
  shopAvatar: { width: 30, height: 30, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.brandPale },
  shopAvatarImage: { width: 28, height: 28, borderRadius: 14 },
  messageCustomer: { maxWidth: '86%', backgroundColor: colors.brand, borderRadius: 18, borderBottomRightRadius: 5, paddingHorizontal: 13, paddingVertical: 9 },
  messageStaff: { maxWidth: '86%', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 18, borderBottomLeftRadius: 5, paddingHorizontal: 13, paddingVertical: 9 },
  messageText: { color: colors.textBody, lineHeight: 20 },
  messageTextCustomer: { color: colors.white },
  timestamp: { color: colors.textSubtle, fontSize: 10, marginTop: 6 },
  timestampCustomer: { color: 'rgba(255,255,255,0.7)', textAlign: 'right' },
  messageImageRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 8 },
  messageImage: { width: 92, height: 92, borderRadius: 10, backgroundColor: colors.brandMist },
  typingBubble: { minWidth: 128, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  typingText: { color: colors.textMuted, fontSize: 12, fontStyle: 'italic' },
  typingDots: { color: colors.brand, fontSize: 14, letterSpacing: 2, marginLeft: 8 },
  conversationNotice: { flexDirection: 'row', alignItems: 'center', gap: 9, marginTop: spacing.md, padding: spacing.md, borderRadius: radii.md, backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border },
  conversationNoticeText: { flex: 1, color: colors.textMuted, fontSize: 12, lineHeight: 17 },
  noticeAction: { minHeight: 32, justifyContent: 'center', paddingHorizontal: 10, borderRadius: radii.pill, backgroundColor: colors.brandSoft },
  noticeActionText: { color: colors.brandDark, fontSize: 11, fontWeight: '800' },
  closedNotice: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: spacing.md, paddingHorizontal: spacing.md, paddingVertical: 8, borderRadius: radii.pill, backgroundColor: '#E9EDF0' },
  closedNoticeText: { color: colors.textMuted, fontSize: 11 },
  composerPanel: { backgroundColor: colors.surface, borderTopWidth: 1, borderTopColor: colors.border, paddingHorizontal: spacing.md, paddingTop: 10, paddingBottom: 8 },
  composerImages: { gap: 8, paddingBottom: 9 },
  composerImageFrame: { position: 'relative' },
  composerImage: { width: 62, height: 62, borderRadius: 10, backgroundColor: colors.brandMist },
  removeImageButton: { position: 'absolute', top: -5, right: -5, width: 22, height: 22, borderRadius: 11, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.text },
  composerRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  attachButton: { position: 'relative', width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.brandSoft },
  attachmentBadge: { position: 'absolute', top: -2, right: -2, minWidth: 17, height: 17, borderRadius: 9, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, backgroundColor: colors.coral, borderWidth: 2, borderColor: colors.surface },
  attachmentBadgeText: { color: colors.white, fontSize: 9, fontWeight: '900' },
  chatInput: { flex: 1, minHeight: 42, maxHeight: 112, borderRadius: 21, borderWidth: 1, borderColor: colors.border, backgroundColor: colors.field, paddingHorizontal: 15, paddingTop: 10, paddingBottom: 9, color: colors.text, fontSize: 15, lineHeight: 20, textAlignVertical: 'top' },
  sendButton: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.brand },
  sendButtonDisabled: { backgroundColor: colors.borderStrong },
  composerFooter: { minHeight: 27, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingLeft: 50, paddingTop: 4 },
  composerHint: { color: colors.textSubtle, fontSize: 10 },
  closeTicketAction: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 4, paddingVertical: 4 },
  closeTicketText: { color: colors.danger, fontSize: 11, fontWeight: '700' },
  chatLoading: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing.sm },
});
