import { StyleSheet } from 'react-native';
import { colors, radii, spacing } from '../../theme';

export const supportStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.background },
  header: { minHeight: 64, backgroundColor: colors.brand, flexDirection: 'row', alignItems: 'center', paddingHorizontal: spacing.lg, gap: 12 },
  back: { width: 40, height: 40, alignItems: 'center', justifyContent: 'center' },
  headerTitle: { color: colors.white, fontSize: 20, fontWeight: '800', flex: 1, textAlign: 'center' },
  content: { padding: spacing.lg, gap: spacing.lg, paddingBottom: 40 },
  search: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.sm, padding: 14, fontSize: 15, color: colors.text },
  hero: { backgroundColor: colors.brandDark, borderRadius: radii.md, padding: spacing.xl, gap: 8 },
  heroTitle: { color: colors.white, fontSize: 22, fontWeight: '800' },
  heroText: { color: '#D9E5EC', lineHeight: 20 },
  button: { backgroundColor: colors.brand, minHeight: 48, borderRadius: radii.sm, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 16 },
  buttonText: { color: colors.white, fontWeight: '800' },
  secondaryButton: { backgroundColor: colors.brandMist },
  secondaryText: { color: colors.brandDark, fontWeight: '800' },
  sectionTitle: { color: colors.text, fontSize: 18, fontWeight: '800' },
  card: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.sm, padding: spacing.lg, gap: 8 },
  cardTitle: { color: colors.text, fontWeight: '800', fontSize: 15 },
  muted: { color: colors.textMuted, lineHeight: 20 },
  faqAnswer: { color: colors.textBody, lineHeight: 21, paddingTop: 6 },
  row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  badge: { backgroundColor: colors.coral, minWidth: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  badgeText: { color: colors.white, fontWeight: '800', fontSize: 12 },
  chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { paddingVertical: 9, paddingHorizontal: 12, borderRadius: 999, backgroundColor: colors.brandMist },
  chipActive: { backgroundColor: colors.brand },
  chipText: { color: colors.brandDark, fontWeight: '700', fontSize: 12 },
  chipTextActive: { color: colors.white },
  input: { backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: radii.sm, padding: 14, color: colors.text, fontSize: 15 },
  label: { color: colors.text, fontWeight: '800', marginBottom: -6 },
  error: { backgroundColor: colors.dangerSoft, color: colors.danger, padding: 12, borderRadius: radii.sm },
  success: { backgroundColor: colors.brandMist, color: colors.brandDark, padding: 12, borderRadius: radii.sm },
  imageRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  image: { width: 80, height: 80, borderRadius: radii.sm, backgroundColor: colors.brandMist },
  messageCustomer: { alignSelf: 'flex-start', maxWidth: '85%', backgroundColor: colors.surface, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 12 },
  messageStaff: { alignSelf: 'flex-end', maxWidth: '85%', backgroundColor: colors.brandMist, borderRadius: 14, padding: 12 },
  messageText: { color: colors.textBody, lineHeight: 20 },
  timestamp: { color: colors.textSubtle, fontSize: 10, marginTop: 6 },
});
